{% set version = '1.57-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat/spatstat_{{ version }}.tar.gz
  sha256: 79ffe4bde48c5e196dedc4347deccb4daa6703d72672c851a9e24af18a81fcd6

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-abind
    - r-deldir >=0.0_21
    - r-goftest
    - r-mgcv
    - r-nlme
    - r-polyclip >=1.5_0
    - r-rpart
    - r-spatstat.data >=1.4_0
    - r-spatstat.utils >=1.13_0
    - r-tensor
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-abind
    - r-deldir >=0.0_21
    - r-goftest
    - r-mgcv
    - r-nlme
    - r-polyclip >=1.5_0
    - r-rpart
    - r-spatstat.data >=1.4_0
    - r-spatstat.utils >=1.13_0
    - r-tensor

test:
  commands:
    - $R -e "library('spatstat')"           # [not win]
    - "\"%R%\" -e \"library('spatstat')\""  # [win]

about:
  home: http://www.spatstat.org
  license: GPL (>= 2)
  summary: Comprehensive open-source toolbox for analysing Spatial Point Patterns.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
