travis:
  secure:
    BINSTAR_TOKEN: BTjTxsI39ksWS7YpyRGZw8YJN1Kdl6lPHk0b32E1Wn47wOrTQTlPwVystXhCTPzvIUGCmNVGNne2nAYASj30SWn/FjQPIL3A2+ldUl5t/IV6rZ9OJ7xauZaVTWHgpBlA/vz9MsmjlLTO8flZ8E2XGLq0/i/yT5TSMPVWh1lHPYQomqRaJw3g7zwB9sG9j578ToezQ3o9lWM4k3WPht/d6glC2IXZ8YdKfAuE1Mbd6lqfn9nttPedq3XQtpjfT6e+KDBFr4QjVgKsO+AaS1EkwmWzUeWB1llH7ymNCSSprRk3K0FowFHKUmtXHiX14gzwrQB7DLOm9AmpK8MVnY0KmcVcz6gqs8m8gOaIvEJRGn4mJxOd0NE/tgr0z2kPP8GXgPdhyD9WIovmp1Zja9p01rZzts6fH4n+uFWdMktxo7R8wFtM8uLwzXTJy+TKUfakJFJ/pK+g3VCRHGfIyzCUH6QrQbvzFRUASnT8qieRfBXgp5yGI5Mi5yftVet77rBMtWA55xGK+APpr1QwHw2Fhakg58hJmBrAOvGnfrC8sawpwPYfFzMH1wNNILWUMW0h8eOE64PfmXbgNS4OqKpEAAhA5iSYmsIYTI9yQ50mhKRsqEWDWOXB4WpsMr6n56/3GRVq5AGYh58UAr/SeoQzOA/h3jYRzejyH7ku4Zy8tHg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
