travis:
  secure:
    BINSTAR_TOKEN: sD49rEuA1TPcyybOAL0/8KORUgNHvXxQYKTsrRPNuB+gK/eW7dNMzmdSzib0Idh6JpQr8cpLUrkN+9o3j6xZRqcJgGKyU8uaBl4qqFAl3mDrDIdYMgmVdyLWjSvWkv2LLT/XezDjrc9qcZJRj9YmSGbfDnVBZnbegQGJwrSPzo4ORARiJ2XPQ5HYMaZrJZxq+rJqOr3lmAXlHZriXruLzm+n103HcHXsXhCJVYZzgE9TYHMa1e4ZJB1U4ZG/+AUAh5f5Ein2UHrKBqnHrZwN5IOcNlXG6wv7NZ7vZsyvLcuI2nlffDfQ4w2VaavPySCrIJZlNkFRlS5lBz9LxfbHNzvw7l1byTaFmxGbaxfaApp9xVI/1tvVOdFPQSewkhPuORtRBK+dPQl8GZZlfrxOyBoUQRhdKGM8BbqwPJSG/4U3ZL6LqiHXQ2YVc4zag+0QX6CRU5bZBYZ7+vJvPPOrT6wCNPFfy6ReJW24/7SNP/Y+vsG35ruWKonEpnd/yrlPtKNRSasEgc4Ebd1C5k8tUbrnEw8+lM7MsWmwrene0HK3/rr5vIudRfucYXg34IlC0d/UWhdNFBBB7tDs1bwsR3JNSlWWIPAB++k26cY8WTkDSZ5tgzVh8oFmfUJC7I74Br84F5+pzLvJF90xUSK8BDpKZcbb+qlsfbZMr/U8ctM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
